version: "3"

services:
  aapanel:
    build: 
      context: ./bin/aapanel
    container_name: 'aapanel-webserver'
    ports:
      - "${AAPANEL_PORT}:8888"
      - "${WEBSERVER_HOST_PORT}:80"
      - "${WEBSERVER_SECURE_HOST_PORT}:443"
      - "${PHPMYADMIN_PORT}:888"
    volumes: 
      - ${WEBSITE_DATA}:/www/wwwroot
      - ${MYSQL_DATA}:/www/server/data
      - ${VHOST_DATA}:/www/server/panel/vhost
      - ${WEBSITE_LOG}:/www/wwwlogs
  redis:
    container_name: 'redis-service'
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"